import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const m_plus_rounded_1c_bold = M_PLUS_Rounded_1c({
  weight: "700",
  subsets: ["latin"],
})
const m_plus_rounded_1c = M_PLUS_Rounded_1c({
  weight: "500",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Ling Fill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="header-bg-height bg-cyan-500 flex items-center pl-4">
        <h1 className={`text-lg ${m_plus_rounded_1c_bold.className}`}>
          Lingo Fill
        </h1> 
      </div>
      <div className={m_plus_rounded_1c.className}>{children}</div>
    </html>
  );
}
