import type { Metadata } from "next";
import { m_plus_rounded_1c } from "@/store/fontStore";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Ling Fill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Lingo-Fill: Learn Languages Effectively</title>
        <meta name="description" content="Join Lingo-Fill to discover a new way of learning languages with interactive courses and real-life practice." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={` ${m_plus_rounded_1c.className}`}>
        {children}
      </body>
    </html>
  );
}
