import type { Metadata } from "next";
import { m_plus_rounded_1c } from "@/store/fontStore";
import "../globals.css";
import SidebarComponent from "@/components/sidebar/Sidebar";
import HeaderComponent from "@/components/header/Header";
import Head from "next/head";

// export const metadata: Metadata = {
//   title: "Ling Fill",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className={` flex w-screen h-screen ${m_plus_rounded_1c.className}`}>
        <SidebarComponent />
        <div className=" h-screen w-screen">
          <HeaderComponent />
          <div className=" h-5/6">{children}</div>
        </div>  
      </div>
    </div>
  );
}
